services:
  db:
    image: arangodb:3.11
    restart: always
    environment:
      - ARANGO_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "127.0.0.1:8529:8529"
    volumes:
      - db_data:/var/lib/arangodb3

  backend:
    build: ./backend
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - backend

volumes:
  db_data:
